export {
  analyzeArchitecture,
  detectFramework,
  detectExternalServices,
  scanApiRoutes,
  analyzeImports,
  classifyFileLayer,
  type ArchitectureAnalysis,
  type ArchitectureComponent,
  type ArchitectureConnection,
  type FrameworkType,
  type LayerType,
  type ComponentType,
  type FileInfo,
  type ImportInfo,
  type ExportInfo,
  type FileNode,
  type LayerGroup,
  type DataFlowPath,
  type DetectedPattern,
  type ArchitectureMetrics,
} from './analyzer'
